name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create Windows requirements file
      run: |
        # Criar um requirements-windows.txt a partir do requirements.txt
        python -c "
        with open('requirements.txt', 'r') as f:
            lines = f.readlines()
        with open('requirements-windows.txt', 'w') as f:
            for line in lines:
                if 'PyQt5-Qt5==' not in line:
                    f.write(line)
        "
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements-windows.txt
            
    - name: Build with PyInstaller
      run: |
        pyinstaller podium-windows.spec
    
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/